# Generated by Django 4.0.5 on 2022-10-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coursetype'),
        ),
    ]
