# Generated by Django 4.0.5 on 2022-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classroomtype_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
