# Generated by Django 4.0.5 on 2022-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_facultytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytype',
            name='type',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('HOD', 'Head of Department'), ('FAC', 'Faculty'), ('VF', 'Visiting Faculty'), ('RF', 'Research Faculty'), ('AF', 'Adjunct Faculty'), ('PF', 'Part Time Faculty'), ('ASST', 'Assistant'), ('LAB ASST.', 'Lab Assistant'), ('LAB ATT.', 'Lab Attendant'), ('LAB INCH.', 'Lab Instructor'), ('LAB TECH.', 'Lab Technician'), ('LAB SUPER.', 'Lab Supervisor'), ('LAB COORD.', 'Lab Coordinator'), ('LAB MANAGER', 'Lab Manager')], max_length=100, unique=True),
        ),
    ]
