# Generated by Django 4.0.5 on 2022-10-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_facultytype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.facultytype'),
        ),
    ]
