# Generated by Django 4.0.5 on 2022-10-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_faculty_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='branch',
        ),
    ]
